# This docker-compose file is used to run the project in Docker for runner or recorder development.
# The local files are mounted into the created container.
#
# Usage:
#  ln -s docker-compose.runner-dev.yml docker-compose.override.yml
#  docker-compose up [-d]
#
# To go back to running the published image:
#  rm docker-compose.override.yml

version: "3.8"

services:
  runner:
    volumes:
      - ./runner/src:/src:cached
      - ./runner/scripts:/scripts:cached
      - ./runner/files:/root/files:cached
