# configure the pipeline to run based on different triggers
# see https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#triggers
trigger:
  - master

resources:
  containers:
    - container: qawolf
      image: qawolf/qawolf:latest

pool:
  vmImage: "ubuntu-16.04"

container: qawolf

steps:
  - script: qawolf test
    env:
      # output artifacts
      QAW_DOM_PATH: $(System.DefaultWorkingDirectory)/artifacts
      QAW_LOG_PATH: $(System.DefaultWorkingDirectory)/artifacts
      QAW_VIDEO_PATH: $(System.DefaultWorkingDirectory)/artifacts
      # # configure tests with environment variables
      # # set "QAW_URL" to override the url for all tests
      # QAW_URL: www.my_staging_url.com
      # # set "QAW_TESTNAME_URL" to override the url for the test named "testname"
      # QAW_CREATE_ACCOUNT_URL: www.mysite.com/createaccount
      # # set "QAW_TESTNAME_0" to override values[0] for the test named "testname"
      # QAW_LOGIN_0: "my_username"

  - publish: $(System.DefaultWorkingDirectory)/artifacts
    artifact: artifacts
    condition: always()
