name: publish to docker hub
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build and publish to docker hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: qawolf/qawolf
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
