name: publish to docker hub
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1 # shallow clone
      - name: build and publish to docker hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: qawolf/qawolf
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
