name: Linux
on:
  push:
    branches:
      - master
  pull_request:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    env:
      QAW_ARTIFACT_PATH: ${{ github.workspace }}/artifacts
      QAW_LOG_LEVEL: debug

    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm run bootstrap

      - run: npm run test

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: firefox
          path: ${{ github.workspace }}/artifacts

    timeout-minutes: 20
