# WARNING: DO NOT ADD SECRETS TO THIS WORKFLOW!!!!
# This workflow is trigged by pull_request and secrets could be exposed in a PR.
# If someone modifies this in a fork it will only expose their secrets (unless we merge it).
# https://github.community/t5/GitHub-Actions/GitHub-Action-workflow-is-executed-for-a-PR-from-a-forked-repo/td-p/29579
name: npm test ubuntu
on:
  push:
    branches:
      - master
  pull_request:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: ["10", "12"]

    env:
      QAW_ARTIFACT_PATH: ${{ github.workspace }}/artifacts
      QAW_LOG_LEVEL: debug
      QAW_SLEEP_MS: 0
      QAW_TEST_URL: http://localhost:5000/

    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm run bootstrap

      - run: npm test

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: ${{ github.workspace }}/artifacts

    services:
      theinternet:
        image: gprestes/the-internet@sha256:f741ba048b7232ef90b0f7885de7f6ac42a52a17e73dd82afc484da140398796
        ports:
          - 5000:5000

    timeout-minutes: 20
