name: QA Wolf Windows Tests

on: [push]

jobs:
  test:
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        test: [unit]

    env:
      QAW_ARTIFACT_PATH: ${{ github.workspace }}\artifacts

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - uses: actions/checkout@v2

      - run: npm install

      - run: npm run build

      - name: Start sandbox
        run: |
          start-process npm -ArgumentList "run test:server" -WindowStyle hidden
          npx wait-on http://localhost:5000

      - run: npm link && npm link qawolf

      - run: npm test
        if: matrix.test == 'unit'

      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: ${{ github.workspace }}\artifacts

    timeout-minutes: 20
